[workspace]
resolver = "2"
members = []


[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.83"
authors = ["i10416"]
homepage = "https://github.com/i10416/effective-rust"
repository = "https://github.com/i10416/effective-rust"
